#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Dec 15 01:09:16 2018
4
@author: aaronpui
"""


import sqlite3

conn = sqlite3.connect('UTSEUS-shanghai-weibo-2012.db')
c = conn.cursor()

c.execute('SELECT * FROM weibo_status')

weibo = c.fetchall()


### to transform into pandas dataframe

import pandas as pd

labels = ['id', 'status', 'user_id', 'location_id', 'date',
          'bow']

df = pd.DataFrame.from_records(weibo,columns=labels)


df_depression = df[[stat is not None and '伤心' in stat for stat in df['status']]]
